name: CI

on:
  push:
    branches: [main]


jobs:
  test:
    runs-on: ubuntu-latest
    defaults:
     run:
       working-directory: TRABALHO-INDIVIDUAL-main/back_projeto
      
    steps:
      - uses: actions/checkout@v3
      - name: Instalar dependências
        run: npm install
      - name: Rodar testes
        run: npm test --coverage
